#!/bin/bash

set -eu

function usage() {
  echo "用法: $(basename $0) <command> [args...]"
  echo "命令:"
  echo "   help     显示详细帮助信息"
  echo "   create   创建一个依赖 lpss 的新项目"
  echo "   node     lpss 节点工具"
  echo "   topic    lpss 话题工具"
  echo "   graph    前后端分离的 lpss 节点图工具"
  echo "   viz      前后端分离的 lpss 3D 可视化工具"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

command=$1
shift

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.lpss"

case "$command" in
  help)
    sps="      "
    echo "$sps┌────────────────────────────────────────────────────────────────────┐"
    echo "$sps│ LPSS 是一个轻量级的发布订阅通信框架，采用去中心化设计，提供 NDP 和 │"
    echo "$sps│ EDP 两层服务发现机制，以及 MTP 话题消息传输协议，提供类似 ROS2 的  │"
    echo "$sps│ *.msg 消息接口，以及部分消息转换函数，由 RMVL 提供支持。此外，本工 │"
    echo "$sps│ 具提供了 LPSS 相关的命令行工具，具体使用方法如下。                 │"
    echo "$sps└────────────────────────────────────────────────────────────────────┘"
    usage
    echo -e "\n更多信息请参考官方手册:"
    echo -e "  使用教程: \033[32mhttps://cv-rmvl.github.io/docs/2.x/d3/d8e/tutorial_modules_lpss.html\033[0m"
    echo -e "  API 文档: \033[32mhttps://cv-rmvl.github.io/docs/2.x/d7/de3/group__lpss.html\033[0m"
    ;;
  create)
    "$script_dir/create.bash" "$@"
    ;;
  node)
    "$script_dir/node.bash" "$@"
    ;;
  topic)
    "$script_dir/topic.bash" "$@"
    ;;
  graph)
    if [ -f "$script_dir/_autogen_lpss_graph" ]; then
      "$script_dir/_autogen_lpss_graph" "$@"
    else
      echo "lpss graph 工具尚未实现。敬请期待！"
    fi
    ;;
  viz)
    if [ -f "$script_dir/_autogen_lpss_viz" ]; then
      "$script_dir/_autogen_lpss_viz" "$@"
    else
      echo "lpss viz 工具尚未实现。敬请期待！"
    fi
    ;;
  *)
    echo "未知命令: $command"
    usage
    exit 1
    ;;
esac

