#!/bin/bash

set -e

function usage() {
  echo -e "\033[1m用法:\033[0m \033[36m$(basename "$0")\033[0m <command> [args...]"
  echo ""
  echo -e "\033[1m命令:\033[0m"
  echo -e "  \033[36mhelp\033[0m      显示详细帮助信息"
  echo -e "  \033[36mcreate\033[0m    创建一个新的 RMVL 模块"
  echo -e "  \033[36mupdate\033[0m    更新 RMVL 或 rmvl-dev-tools 工具"
  echo -e "  \033[36mdev\033[0m       开始开发 RMVL"
  echo -e "  \033[36mremove\033[0m    移除 RMVL 组件"
  echo -e "  \033[36mversion\033[0m   显示 rmvl-dev-tools 工具版本"
}

function print_help_banner() {
  local sps="      "
  local c="\033[33;1m" # 黄色加粗
  local r="\033[0m"    # 重置颜色
  
  printf "${sps}${c}╭──────────────────────────────────────────────────────────────────────────╮${r}\n"
  printf "${sps}${c}│${r} RMVL 最初是面向 RoboMaster 赛事的视觉库，现在此之上逐步完善有关基础算法、${c}│${r}\n"
  printf "${sps}${c}│${r} 机器视觉、通信的功能，旨在打造适用范围广、使用简洁、架构统一、功能强大的 ${c}│${r}\n"
  printf "${sps}${c}│${r} 视觉控制一体库。本工具提供了 RMVL 相关的命令行工具，具体使用方法如下。   ${c}│${r}\n"
  printf "${sps}${c}╰──────────────────────────────────────────────────────────────────────────╯${r}\n"
}

if [ -z "${RMVL_ROOT_:-}" ]; then
  echo -e "\033[31mRMVL_ROOT_ 未定义。请将 RMVL_ROOT_ 设置为 RMVL 仓库的根目录。\033[0m"
  exit 1
fi

if [ "$#" -lt 1 ]; then
  usage
  exit 1
fi

command=$1
shift

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.rmvl"

case "$command" in
  help)
    print_help_banner
    usage
    echo -e "\n此工具支持的根命令有: \033[33mrmvl\033[0m、\033[33mlpss\033[0m 和 \033[33mlviz\033[0m，更多信息请参考官方手册:"
    echo -e "  用户手册: \033[32mhttps://cv-rmvl.github.io/\033[0m"
    echo -e "  API 文档: \033[32mhttps://cv-rmvl.github.io/docs/2.x/\033[0m"
    echo -e "  GitHub:   \033[32mhttps://github.com/cv-rmvl/rmvl\033[0m"
    ;;
  create)
    "$script_dir/create.bash" "$@"
    ;;
  update)
    "$script_dir/update.bash" "$@"
    ;;
  dev)
    "$script_dir/dev.bash" "$@"
    ;;
  remove)
    "$script_dir/remove.bash" "$@"
    ;;
  version)
    "$script_dir/version.bash" "$@"
    ;;
  *)
    echo "未知命令: $command"
    usage
    exit 1
    ;;
esac

