#!/bin/bash

set -e

function usage() {
  echo "用法: $(basename $0) <command> [args...]"
  echo "命令:"
  echo "   help     显示此帮助信息"
  echo "   create   创建一个新的 RMVL 模块"
  echo "   update   更新 RMVL 或 rmvl-dev-tools 工具"
  echo "   dev      开始开发 RMVL"
  echo "   remove   移除 RMVL 组件"
  echo "   version  显示 RMVL 版本"
}

if [ -z "${RMVL_ROOT:-}" ]; then
  echo -e "\033[31mRMVL_ROOT 未定义。请将 RMVL_ROOT 设置为 RMVL 仓库的根目录。\033[0m"
  exit 1
fi

if [ "$#" -lt 1 ]; then
  usage
  exit 1
fi

command=$1
shift

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.rmvl"

case "$command" in
  help)
    usage
    ;;
  create)
    "$script_dir/create.bash" "$@"
    ;;
  update)
    "$script_dir/update.bash" "$@"
    ;;
  dev)
    "$script_dir/dev.bash" "$@"
    ;;
  remove)
    "$script_dir/remove.bash" "$@"
    ;;
  version)
    "$script_dir/version.bash" "$@"
    ;;
  *)
    echo "未知命令: $command"
    usage
    exit 1
    ;;
esac

